name: Build and Test CI for Pull Requests

on:
  pull_request:
    branches: [ 'master', 'develop' ]
  workflow_dispatch:

jobs:

  build-focal:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Checkout submodule
      run: git submodule update --init --depth 1 description/media

    - name: Build, test
      run: ./scripts/docker/build.sh --focal --remote
                                     astrobee test_astrobee
